version: '3.8'
services:
  nginx:
    container_name: web
    restart: on-failure
    image: nginx:1.19.8
    volumes:
      - ./nginx/prod/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    links:
      - web
  web:
    container_name: backend
    build: .
    restart: always
    env_file: dev.env
    command: gunicorn HSEQuest.wsgi:application --bind 0.0.0.0:5000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12.0-alpine
    env_file: dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  smtp-server:
    image: mailhog/mailhog
    expose:
      - 1025
      - 8025
    ports:
      - '1025:1025'
      - '8025:8025'
volumes:
  media_volume:
  static_volume:
  postgres_data:
